model_list:
  - model_name: friendly_model_name # EDIT w/name litellm advertises from API. gpt-4o in my config
    litellm_params:
      model: azure/your_full_model_name # EDIT w/full model name you've configured on Azure
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: os.environ/AZURE_API_VERSION # runs os.getenv("AZURE_API_VERSION")
  #   rpm: 240 # optional
  # - model_name: friendly_model_name_mini # optional - gpt-4o-mini in my config
  #   litellm_params:
  #     model: azure/your_full_model_name_2 # you get it...
  #     api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
  #     api_key: os.environ/AZURE_API_KEY # runs os.getenv("AZURE_API_KEY")
  #     api_version: os.environ/AZURE_API_VERSION # runs os.getenv("AZURE_API_VERSION")
  #     rpm: 240 # optional